#!/usr/bin/env python3

import sys
import socket
import yaml
import threading

file = open('config.yml', 'r')
data = yaml.safe_load(file)

ip_list = list(data.keys())
ports_list = list(data.values())

def port_scan(ip, ports):
    """ Check sockets for some ip address of network host """

    try:
        for port in ports:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(0.5)
            conn = sock.connect_ex((ip, port))
            if conn == 0:
                print('{0:<20}{1:>5} open'.format(ip, port))
            else:
                print('{0:<20}{1:>5} closed'.format(ip, port))
            sock.close()
    except KeyboardInterrupt:
        print("Interrupted by Ctrl+C")
        sys.exit()
    except socket.gaierror:
        print('Hostname could not be resolved.')
    except socket.error:
        print('Could not connect to server.')

def main(ip_list, ports_list):
    """ Check sockets status for list of ip addresses """

    for i in range(len(ip_list)):
        ip = ip_list[i]
        ports = ports_list[i]
        port_scan_threading = threading.Thread(target=port_scan, kwargs={'ip': ip,'ports': ports})
        port_scan_threading.start()

if __name__ == '__main__':
    main(ip_list, ports_list)

