#!/usr/bin/env python3

"""Usage:
        netsocks [-g group][-L group][-al][-h,--help]

   Options:
       -a            to check sockets for all host groups
       -g <group>    to check sockets for selected group of hosts
       -l            print list of all existing groups
       -L <group>    print list of hosts in specific group name
       -h --help     this help message

"""
import os
import sys
import socket
import oyaml as yaml
import threading
from datetime import datetime
from docopt import docopt

now = datetime.now()
dt_string = now.strftime("%d/%m/%Y %H:%M:%S")

config_db = {}
all_host_groups = {}

data = {}

ports_scan_result = ''

def get_config_file():
    """ default config file is expected in same directories """

    script_path = os.path.realpath(__file__)
    default_config_file = script_path + ".yml"
    return default_config_file

def get_config(config=get_config_file()):
    """ Getting config from a YAML file """

    global config_db
    try:
        with open(config, 'r') as stream:
            config_db = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
            print(exc)
            sys.exit()
    except FileNotFoundError:
            print("Not found such file or directory: {}".format(config))
            sys.exit()
    return config_db

def get_all_host_groups():
    """ Getting data of all exists host groups for their socks checking """

    global all_host_groups

    groups_list = list(config_db.keys())
    for i in range(len(groups_list)):
        added_group = config_db.get(groups_list[i])
        all_host_groups = {**all_host_groups, **added_group}
    return all_host_groups

def get_all_groups_list():
    """ Printing list of all exists groups """

    groups_list = list(config_db.keys())
    for i in range(len(groups_list)):
        print(groups_list[i])

def get_all_hosts_list(group):
    """ View all hosts in specific group """

    try:
        hosts_list = list(group.keys())
        for i in range(len(hosts_list)):
            print(hosts_list[i])
    except AttributeError:
        print("Not found such group, correct your input and try again...")
        get_all_groups_list()

def printProgressBar (iteration, total,
                      prefix = '', suffix = '', decimals = 1,
                      length = 100, fill = '█', printEnd = "\r"):
    """
    Call in a loop to create terminal progress bar
    @params:
        iteration   - Required  : current iteration (Int)
        total       - Required  : total iterations (Int)
        prefix      - Optional  : prefix string (Str)
        suffix      - Optional  : suffix string (Str)
        decimals    - Optional  : positive number of decimals in percent complete (Int)
        length      - Optional  : character length of bar (Int)
        fill        - Optional  : bar fill character (Str)
        printEnd    - Optional  : end character (e.g. "\r", "\r\n") (Str)
    """
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
    filledLength = int(length * iteration // total)
    bar = fill * filledLength + '-' * (length - filledLength)
    print('\r%s |%s| %s%% %s' % (prefix, bar, percent, suffix), end = printEnd)
    # Print New Line on Complete
    if iteration == total:
        print()

def port_scan(ip, ports):
    """ Check sockets for some one ip address of network host """

    global ports_scan_result

    for port in ports:
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(0.5)
            conn = sock.connect_ex((ip, port))
            if conn == 0:
                ports_scan_result += ('{0:<20}{1:>5} open\n'.format(ip, port))
            else:
                ports_scan_result += ('{0:<20}{1:>5} closed\n'.format(ip, port))
            sock.close()
        except socket.gaierror:
            print('Hostname could not be resolved.')
        except socket.error:
            print('Could not connect to server.')

def main(ip_list, ports_list):
    """ Check sockets status for list of ip addresses """

    global ports_scan_result
    ports_scan_result += ('Checked at {}\n'.format(dt_string))
    ports_scan_result += ("-" * 30 + "\n")

    # Initial call to print 0% progress
    printProgressBar(0, ip_list_length, length = 22)
    for i in range(ip_list_length):
        try:
            ip = ip_list[i]
            ports = ports_list[i]
            port_scan_threading = threading.Thread(target=port_scan,
                                                   kwargs={'ip': ip,'ports': ports})
            port_scan_threading.start()
            port_scan_threading.join()
            ports_scan_result += ("-" * 30 + "\n")
            printProgressBar(i + 1, ip_list_length, length = 22)
        except KeyboardInterrupt:
            print("Interrupted by Ctrl+C")
            sys.exit()

    print(ports_scan_result)


if __name__ == '__main__':

    get_config()

    args = docopt(__doc__)

    if args['-L']:
        get_all_hosts_list(config_db.get(args['-L']))
        sys.exit()
    elif args['-l']:
        get_all_groups_list()
        sys.exit()
    elif args['-g']:
        data = config_db.get(args['-g'])
    elif args['-a']:
        data = get_all_host_groups()
    else:
        print(__doc__)
        sys.exit()

    try:
        ip_list = list(data.keys())
    except AttributeError:
        print("Not found such group, correct your input and try again...")
        get_all_groups_list()
        sys.exit()
    ports_list = list(data.values())
    ip_list_length = len(ip_list)

    main(ip_list, ports_list)

